### ISSUE TITLE
Incorrect key when opening kdbx4

### ISSUE THREAD

**Issue by deeuu** [sseemayer/keepass-rs#212] opened 2024-02-07 19:16 UTC
Hi,

Possibly related to #59: I'm unable to open a KDBX4 database, created on `KeePassXC`, when encrypted with both a password and keyfile. No issue when loading a password-only protected database (so without the keyfile).

```rust
use std::fs::File;
use keepass::{Database, DatabaseKey};

fn main() {
    let keyfile = &mut File::open("./secret.keyx").unwrap();
    let key = DatabaseKey::new()
        .with_password("secret")
        .with_keyfile(keyfile).unwrap();

    let db_file = &mut File::open("./secrets.kdbx").unwrap();
    let _ = Database::open(db_file, key).unwrap();
}
```
yields the error ```called `Result::unwrap()` on an `Err` value: Key(IncorrectKey)```.

I've [attached](https://github.com/sseemayer/keepass-rs/files/14200513/project.zip) a little reproducible which includes the fake database and keyfile.

Additional info:
`keepass-rs` version 0.7.3
KeePassXC 2.7.6
Encryption algo: AES 256-bit
KDF: Argon2d (KDBX 4 - recommended)
System: Apple M1 arm64

Let me know if you need anything else.

Thanks!

**Comment by louib** [comment] 2024-02-08 02:51
@deeuu thanks for the bug report and steps to reproduce!

Looks like we don't support v2 of the keyfiles yet. I have [a PR](https://github.com/sseemayer/keepass-rs/pull/213) opened to fix that, but I still have to add a few integration tests before it can be merged.

**Closed** 2024-04-28 03:41 UTC
